name: CI Build

on:
  push:
    branches:
    tags:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v2

    - name: install go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: test and build
      run: |
        go test -race -timeout=60s ./...
        go build -race -o datadog-parser ./...

    - name: install golangci-lint
      run: |
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.42.0

    - name: run linters
      run: ./golangci-lint run --config ./.golangci.yml ./... ;

    - name: build image
      run:  docker build --build-arg SKIP_TEST=true --build-arg CI=github .
